### ISSUE TITLE
Gravel Silk Touchability Icon Flickers in WAILA

### ISSUE THREAD

**Issue by gabor7d2** [squeek502/WailaHarvestability#36]
I saw this everywhere. Like in AS2 ME^4, My Modpack that I am making, Infinity, etc.
The problem is in the title, the Silk Touchability Icon Flickers right next to the `Currently Harvestable` text.
[Youtube Video Link](https://youtu.be/vg5EWWHAq6M)

WAILA Version: 1.5.10
WAILA Harvestability Version: 1.1.2

Thanks for the help!
If you need modlist, forge log or anything like that, tell me.

**Comment by squeek502** [comment]
Thanks for reporting this. It's happening because the silk touch handler checks the block's drops to see if silk touch gives a different drop than regular harvesting, but gravel blocks drop flint _instead_ of the gravel block 10% of the time, so the check is currently failing some of the time and succeeding other times, causing the icon to flicker.

I came up with one way to fix it, but I'm not sure it's the best. I'll think about it some more and see if I can come up with anything better.

**Comment by gabor7d2** [comment]
No problem! Thanks! :smile:

**Comment by gabor7d2** [comment]
I found another block that does this: The Cloud Blocks from Chisel (all of them), but this time not just the silk touchability flickers, but the whole line with the `Currently Harvestable` text.
ID: `chisel:cloud`
Does your fix fixes all of these issues ?

**Comment by squeek502** [comment]
Not sure, will look into that.

**Comment by squeek502** [comment]
Committed the fix without realizing it in 3794f40835d972a39d7a42a1b568d5aab17f270c. Should be fixed in v1.1.3.
