### ISSUE TITLE
[1.11.2] Incorrect Machine Name in Tooltip on Thermal Expansion Machines

### ISSUE THREAD

**Issue by Andronomos** [squeek502/WailaHarvestability#55]
Whenever you look at any machine from the Thermal Expansion mod [**(Link)**](https://minecraft.curseforge.com/projects/thermalexpansion) it displays the incorrect name of the machine. They are all called "Redstone Furnace".

In the screenshot below I don't have a Redstone furnace and am looking at an Induction Smelter.
http://i.imgur.com/BFZLsZq.png

**Mod Versions:**

- WailaHarvestability mc1.11-1.1.10
- Forge 1.11.2-13.20.0.2315
- ThermalExpansion 1.11.2-5.2.3.6

**Comment by squeek502** [comment]
Waila Harvestability shouldn't be able to affect this. Does it only happen when Waila Harvestability is installed?

You'll probably want to report this to Waila or Hwyla (whichever you're using), and *maybe* TE. Note, though, that if you're using Waila, it might be fixed by switching from Waila to [Hwyla](https://minecraft.curseforge.com/projects/hwyla), which is an updated fork of Waila; Waila proper has been semi-abandoned in recent versions and has known bugs like this sort of thing.

**Comment by Andronomos** [comment]
@squeek502 Thank you for letting me know. I had no idea this was was semi abandoned due it being updated to recent versions.
