### ISSUE TITLE
[1.16.1-Request] Make minimum required Forge version .88 instead of .91

### ISSUE THREAD

**Issue by Gbergz** [squeek502/WailaHarvestability#71]
Title^

Is this something that can be done?
Many mods broke over .88 and haven't received updates just yet. Would make my life and others a little bit easier. No worries if you can't.

Great mod however!

**-** Gbergz

**Comment by GirafiStudios** [comment]
The issues that .88 causes was later fixed. As long as you're using the latest version of Forge, not mods should be having any problems.

**Comment by Gbergz** [comment]
Yeah I know but as a pack developer this isn't the case. Alot of mods are broken after .89 even on the latest update of forge (.106) makes multiple mods crash aswell.
But I'll try again!

Edit: Yeah it didn't work sadly.

**Comment by GirafiStudios** [comment]
So the thing is, that harvest levels actually won't show properly on all blocks, before Forge version 32.0.105 - due to harvest levels not having been added to new 1.16 yet before that.
In my opinion it's up to the other mods, to make sure they're working with the latest versions of Forge.
If @squeek502 disagrees, I can can change it.
